apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: davidgasquez/cronjob:1.0.0
            imagePullPolicy: Always
          restartPolicy: OnFailure
